spring.datasource.url: jdbc:postgresql://localhost:5432/subpub
spring.datasource.username: ${DB_LOGIN}
spring.datasource.password: ${DB_PASSWORD}
spring.datasource.driver-class-name: org.postgresql.Driver
#spring.datasource.initialization-mode: always
spring.jpa.database: postgresql
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto: create

spring.jpa.defer-datasource-initialization: true
spring.jpa.show-sql: true
spring.main.web-application-type: NONE

socket.server.port: 8000

